sudo: false
language: node_js
node_js:
- '4.0'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - xvfb
    - libpcap-dev
install:
- export CXX="g++-4.8"
- npm install -g gulp electron-prebuilt
- npm install
before_script:
- export DISPLAY=':99.0'
- Xvfb :99 -extension RANDR -screen 0 1024x768x24 > /dev/null 2>&1 &
- export PAPERFILTER_TESTDATA="spec/test"
- export DRIPCAP_UI_TEST=$(pwd)/spec/main
- gulp
script:
- npm test
notifications:
  slack:
    secure: lD8KoxYN3DBs9D6C8XvpX2Jc+myv2tprVqcV5bbK8Ea7gcduiy29vM4i4Vx4eXeeEbXMW0BSnpe1sJ5QO/1vHvFOm8FbPzL5nsxuNCSE/2uL3MufOtJgAzgb/7RQHKSfploG8ajMSBlRpQl9qtMZb8LhoCAZh/czWsIZQwji7r2gdafaRcwh2sgMbO1G/C1W4/IoytrIhe8doi4KBRkC/bt0BarptstlkjMvZTbIKjY0YrB8VZyWqOMO3U6d1+4nKcoL2wsIZeB1UD1RgLkqvFd+4IBDh3fkrKTIftjBfh/manEf+ECzq9e4DkTLoBcGas5MniOILJgzC7R5TOeehYIVui4KHUZx2tbMFaYz+FANsdMtTUCLI46N3QeJpo17noQJ4A1ztecnQ+Q4d+cyROTnhTILv2hQn1LLVe3GLN8fkH0Oj2X4FkY3RPrWDKDeTItlMCGWrSvHM7q+hN6GhbDzDdyzE/OH3HtTr/nacXy3WEsdYIwaoJQOvuDx5/a8JawheEDJIfXE2IAKWn7LfHojKghEEAt4kyhsIMBSpsVkxmV3Tc4wyKSDp6h7/EFNoLP3J2cOClFJZCLeV3VTq5SaRfURTkB8p262m+KokxzLeAzO3xHY95gdbyxHMEQnI1qt19FMtJ1h9ZWALObN64NhevnJpkprgzfZdh6Z42s=
