sudo: false
language: node_js
node_js:
- '4.0'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - xvfb
    - libpcap-dev
    - alien
install:
- export CXX="g++-4.8"
- npm install -g npm_lazy
- npm_lazy > /dev/null 2>&1 &
- npm config set registry http://localhost:8080/
- npm install -g gulp electron-prebuilt
- npm install
before_script:
- export DISPLAY=':99.0'
- Xvfb :99 -extension RANDR -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
- npm test
notifications:
  slack:
    secure: lD8KoxYN3DBs9D6C8XvpX2Jc+myv2tprVqcV5bbK8Ea7gcduiy29vM4i4Vx4eXeeEbXMW0BSnpe1sJ5QO/1vHvFOm8FbPzL5nsxuNCSE/2uL3MufOtJgAzgb/7RQHKSfploG8ajMSBlRpQl9qtMZb8LhoCAZh/czWsIZQwji7r2gdafaRcwh2sgMbO1G/C1W4/IoytrIhe8doi4KBRkC/bt0BarptstlkjMvZTbIKjY0YrB8VZyWqOMO3U6d1+4nKcoL2wsIZeB1UD1RgLkqvFd+4IBDh3fkrKTIftjBfh/manEf+ECzq9e4DkTLoBcGas5MniOILJgzC7R5TOeehYIVui4KHUZx2tbMFaYz+FANsdMtTUCLI46N3QeJpo17noQJ4A1ztecnQ+Q4d+cyROTnhTILv2hQn1LLVe3GLN8fkH0Oj2X4FkY3RPrWDKDeTItlMCGWrSvHM7q+hN6GhbDzDdyzE/OH3HtTr/nacXy3WEsdYIwaoJQOvuDx5/a8JawheEDJIfXE2IAKWn7LfHojKghEEAt4kyhsIMBSpsVkxmV3Tc4wyKSDp6h7/EFNoLP3J2cOClFJZCLeV3VTq5SaRfURTkB8p262m+KokxzLeAzO3xHY95gdbyxHMEQnI1qt19FMtJ1h9ZWALObN64NhevnJpkprgzfZdh6Z42s=
before_deploy:
- gulp linux
- npm run dpkg
- fakeroot alien --to-rpm --scripts dripcap-x64.deb
- mv *.rpm dripcap-x64.rpm
- zip -j paperfilter-linux-x64.zip .build/node_modules/paperfilter/bin/paperfilter
deploy:
  provider: releases
  api_key:
    secure: RZynYJOGSBraBPp18CKTJ5XAefzu/9QgaIzF157BHRJVkIUsGDy8gVtR1W4AyjPP9hmLrpgZF55/lic2P/pY8hHvVCtHDYEeQNuwigs3EY+ZZiCotCQYDXF0mEoPI+6nWtyGo34dhDzIukTofsOEUBsDuLhJyWxc6gmhxfp8N/GhMp6GRkwOPIg56BbqEuZJngiA1xN1DgUbK+U0sKVbEGqUMpGciM8bO9YhkBNEGd1bcYOFiq/ke6EdH+VcG3dvyG2DGI3ZELuy/lboxYhhffvqotrYL0/eyIaZBx817F7kjsNg/Q8R64c/AxBv9L4AoHdOFV+l7Eey8ThA8ysmu7kauEAYvTlOS5wI9N5oQ4E4vEz+nPnfA1+/riOazOcCuDkssaCcHWZunAhGzfEP7HViXNVKbvYhWPv8058/c6JxybBxE7D+goDo9lKYsgW61gHe6Uu39/q1cZh27JoruRJv4k5SXio+fnbkrqtRsEkEbwrwbSnz1r9Gic0ybB5NJVTGMDDzUdUvrIErky+PzRgz2gvk+UUKOdgDkWxCj0nB8Ntgs7TpBlfNLicaq2J7uExDjvqCtllZr5vB3yxnqekT5b+vFyOASLvFjxYt8htdBzLzO675TGJWe9O5eFtMRJ9pwkO7GNt2KlIl7Zn9GvxyGpG8C/0xHqu/7HBwXXU=
  file:
  - dripcap-linux-x64.zip
  - dripcap-x64.deb
  - dripcap-x64.rpm
  - paperfilter-linux-x64.zip
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    - GOPATH: /home/travis/gopath
    - GOBIN: /home/travis/gopath/bin
    - secure: PDTa8agVefW++LH9YNWkSsP/sr4/xWiAylXB+WXIEclLU7WeoyDyIxVXON8mHIt/fKyGGKw5QYC1e1IVAbnARZy+H7IJopeWsbsT9CMIVZuXiSOPFUN2svk1YtXpFbo20QlBbCQPB1mcbdGVShWJOTe4FpYNX3Nav0q66Nes3j8fiiNZa2m7tLfR4aXlwNv0wUtTzzdWC5jzMT73//ZTjuPWV1tIPJUu/a5wxkEhCYXM1why3cH6BMRYRZYGlg++TFacA+Efkjc1FHPs24nahqia4PQ6dkNWb1VxdFKuX+73HX2FaV1IWROung4RbK/+k3x6zBdKXpQJXtZA3F88P8fbRerUczt06CNgZLf85cG9OucoJ/cK16XJbMYzC3B8WKdHlBQTP98Kv59WhrI4+NoGaiNGgpczLfei54Gqqwgp40q6OQalgA/NoYXdxVzBNXT+Gtd/obESqx3z5k5iGhZicShwnMP8ySudjv+oms+PoWtdqKg6rtndsAHbhsi+wQPUK6YmLznUlARVTf2TK5g7CSW2cGjCgUXEwSc1ohFNSOi5iWm/jsgwk3yUxk27TizsiRv9LOLFQLP20ghGh5+DiF5hHJtM+CK9qysAGFXK6IHUdkDjBkjpGOJEWGmSGYSLFid+TKzVCAnQA5OYhml7AMW0bngNcUlDdysvE1s=
