version: 1.0.{build}
install:
- ps: travis\windows-before-install.ps1
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
