version: 1.0.{build}
init:
- ps: Install-Product node 7 x64
environment:
  CL: -DDELAYIMP_INSECURE_WRITABLE_HOOKS
install:
- ps: travis\windows-before-install.ps1
build_script:
- ps: gulp build
test_script:
- ps: gulp out
after_test:
- ps: travis\windows-before-deploy.ps1
artifacts:
- path: dripcap-windows-amd64.zip
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 5xfEThlejgLcJhJS3rNfbbvFPDyuRy+wVgC0/KrbMiWycAYQej7GhAbCVvSneLoT
  artifact: dripcap-windows-amd64.zip
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
